// web/solid/src/App.tsx
import { Show, createEffect, on, onMount } from "solid-js";
import { Icon, TbBtn } from "./parts";
import { Inspector } from "./Inspector";
import { ColumnChooser, ContextMenu, HoverList } from "./Popovers";
import { Sidebar, Statusbar, Topbar } from "./Shell";
import { ProjectTable } from "./Table";
import { Viewbar } from "./Viewbar";
import { load, loadError, loadSidecars, setUi, total, ui, selectedProjects } from "./state";

export function App() {
  onMount(() => { load(); loadSidecars(); });
  // The list follows the scope and the search, nothing else.
  createEffect(on(() => [ui.scope, ui.query], () => { load(); }, { defer: true }));

  const shown = () => ui.inspectorOpen;

  const onKey = (e: KeyboardEvent) => {
    if (e.key === "F2" && ui.renaming == null) {
      const sel = selectedProjects();
      if (sel.length === 1) { e.preventDefault(); setUi("renaming", sel[0].id); }
    }
    if (e.key === "Escape") setUi({ menu: null, popover: null });
  };

  return (
    <div class="win" classList={{ "sidebar-collapsed": ui.sidebarCollapsed, "no-inspector": !shown() }}
      onKeyDown={onKey} tabIndex={-1}
      onClick={(e) => {
        // A click outside any popover closes the open ones.
        if (!(e.target as HTMLElement).closest(".pop, [data-keep]")) setUi({ menu: null, popover: null });
      }}>
      <Topbar />
      <div class="cols">
        <Sidebar />
        <section class="main">
          <div class="viewbar">
            <Viewbar />
            <span class="grow" />
            <TbBtn icon={shown() ? "right_panel_close" : "right_panel_open"} title="Inspector" on={shown()}
              onClick={() => setUi("inspectorOpen", (o) => !o)} />
          </div>
          <div class="content">
            <Show when={loadError()}><div class="error-banner">Cannot reach the daemon: {loadError()}</div></Show>
            <Show when={total() > 0} fallback={
              <Show when={!loadError()}>
                <div class="empty">
                  <Icon name={ui.query ? "search_off" : "inventory_2"} />
                  <h2>{ui.query ? `No projects match “${ui.query}”` : ui.scope === "archived" ? "No archived projects" : "No projects yet"}</h2>
                </div>
              </Show>}>
              <ProjectTable />
            </Show>
          </div>
        </section>
        <Show when={shown()}><Inspector /></Show>
      </div>
      <Statusbar />
      <Show when={ui.menu} keyed>{(m) => <ContextMenu menu={m} />}</Show>
      <Show when={ui.hot} keyed>{(h) => <HoverList hot={h} />}</Show>
      <Show when={ui.popover === "columns"}><ColumnChooser /></Show>
    </div>
  );
}

// web/svelte/src/App.svelte
<script lang="ts">
  import { onMount } from "svelte";
  import ColumnChooser from "./ColumnChooser.svelte";
  import ContextMenu from "./ContextMenu.svelte";
  import HoverList from "./HoverList.svelte";
  import Icon from "./Icon.svelte";
  import Inspector from "./Inspector.svelte";
  import Sidebar from "./Sidebar.svelte";
  import Statusbar from "./Statusbar.svelte";
  import Table from "./Table.svelte";
  import TbBtn from "./TbBtn.svelte";
  import Topbar from "./Topbar.svelte";
  import Viewbar from "./Viewbar.svelte";
  import { data, load, loadSidecars, ui, view } from "./state.svelte";

  onMount(() => { load(); loadSidecars(); });

  // The list follows the scope and the search, nothing else.
  let first = true;
  $effect(() => {
    ui.scope; ui.query;   // the two reads this effect depends on
    if (first) { first = false; return; }
    load();
  });

  function onkeydown(e: KeyboardEvent) {
    if (e.key === "F2" && ui.renaming == null && view.selectedProjects.length === 1) {
      e.preventDefault();
      ui.renaming = view.selectedProjects[0].id;
    }
    if (e.key === "Escape") { ui.menu = null; ui.popover = null; }
  }

  // A click outside any popover closes the open ones.
  function onclick(e: MouseEvent) {
    if (!(e.target as HTMLElement).closest(".pop, [data-keep]")) { ui.menu = null; ui.popover = null; }
  }
</script>

<!-- svelte-ignore a11y_no_noninteractive_tabindex, a11y_click_events_have_key_events, a11y_no_static_element_interactions -->
<div class="win" class:sidebar-collapsed={ui.sidebarCollapsed} class:no-inspector={!ui.inspectorOpen}
  {onkeydown} {onclick} tabindex="-1">
  <Topbar />
  <div class="cols">
    <Sidebar />
    <section class="main">
      <div class="viewbar">
        <Viewbar />
        <span class="grow"></span>
        <TbBtn icon={ui.inspectorOpen ? "right_panel_close" : "right_panel_open"} title="Inspector" on={ui.inspectorOpen}
          onclick={() => (ui.inspectorOpen = !ui.inspectorOpen)} />
      </div>
      <div class="content">
        {#if data.loadError}<div class="error-banner">Cannot reach the daemon: {data.loadError}</div>{/if}
        {#if view.total > 0}
          <Table />
        {:else if !data.loadError}
          <div class="empty">
            <Icon name={ui.query ? "search_off" : "inventory_2"} />
            <h2>{ui.query ? `No projects match “${ui.query}”` : ui.scope === "archived" ? "No archived projects" : "No projects yet"}</h2>
          </div>
        {/if}
      </div>
    </section>
    {#if ui.inspectorOpen}<Inspector />{/if}
  </div>
  <Statusbar />
  <!-- Keyed on the object, so a new menu or hover target is a fresh popover, placed anew. -->
  {#key ui.menu}{#if ui.menu}<ContextMenu menu={ui.menu} />{/if}{/key}
  {#key ui.hot}{#if ui.hot}<HoverList hot={ui.hot} />{/if}{/key}
  {#if ui.popover === "columns"}<ColumnChooser />{/if}
</div>
