// web/svelte/src/Table.svelte
<script lang="ts">
  // The projects table. Rows are keyed by project, so a sort or a page change moves the
  // existing row nodes, and an edit to one project touches only its own cells.
  import { COLUMNS, columnById, nextSort } from "../../shared/projects";
  import Cb from "./Cb.svelte";
  import Icon from "./Icon.svelte";
  import Row from "./Row.svelte";
  import { checkAll, isSelected, sortBy, ui, view } from "./state.svelte";

  const cols = $derived(ui.columns.map(columnById).sort((a, b) => COLUMNS.indexOf(a) - COLUMNS.indexOf(b)));
  const head = $derived.by(() => {
    const ids = view.pageIds;
    const on = ids.filter(isSelected).length;
    return ids.length && on === ids.length ? true : on ? ("mixed" as const) : false;
  });
  const w = (n: number) => `width: calc(var(--u) * ${n})`;
</script>

{#snippet th(id: string, label: string, width: number, num = false)}
  {@const sorted = ui.sort?.col === id}
  <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
  <th class:num class:sorted style={w(width)} onclick={() => sortBy(nextSort(ui.sort, id))}>
    {label}
    {#if sorted}<Icon name={ui.sort!.desc ? "arrow_downward" : "arrow_upward"} />{/if}
    <span class="grip"></span>
  </th>
{/snippet}

<table class="grid fixed">
  <thead>
    <tr>
      <!-- svelte-ignore a11y_click_events_have_key_events, a11y_no_noninteractive_element_interactions -->
      <th class="lead check" style={w(11)} title="Select all on this page" onclick={checkAll}><Cb state={head} /></th>
      <th class="lead" style={w(10)} title="Audition audio"></th>
      {@render th("name", "Name", 100)}
      {@render th("tags", "Tags", 64)}
      {#each cols as c (c.id)}{@render th(c.id, c.label, c.w, c.num)}{/each}
    </tr>
  </thead>
  <tbody>
    {#each view.pageRows as p (p.id)}
      <Row {p} {cols} />
    {/each}
  </tbody>
</table>

// web/solid/src/samples/Table.tsx
// The samples table. Rows are the store's own proxies, so `For` keeps a row's nodes across
// a sort, a page change or a check.

import { For, Show } from "solid-js";
import { fmtBytes, splitPath } from "../../../shared/format";
import { SAMPLE_COLUMNS, folderOf, formatOf, presenceLabel } from "../../../shared/samples";
import type { SampleRow } from "../../../shared/types";
import { Icon } from "../shell/parts";
import { setShell } from "../shell/shell";
import { PresentDot } from "./parts";
import { formats, pageRows, select, sortBy, sui } from "./state";

const cell = (n: number) => ({ width: `calc(var(--u) * ${n})` });

function Head() {
  return (
    <thead>
      <tr>
        <For each={SAMPLE_COLUMNS}>{(c) => {
          const sorted = () => sui.sort?.col === c.id;
          return (
            <th classList={{ num: c.num, sorted: sorted() }} style={cell(c.w)} onClick={() => sortBy(c.id)}>
              {c.label}
              <Show when={sorted()}><Icon name={sui.sort!.desc ? "arrow_downward" : "arrow_upward"} /></Show>
              <span class="grip" />
            </th>
          );
        }}</For>
      </tr>
    </thead>
  );
}

/** A folder truncated in the middle, so the drive and the folder's own name both stay. */
function Folder(props: { path: string }) {
  const folder = () => folderOf(props.path);
  const parts = () => splitPath(folder());
  return (
    <span class="pathcell" title={folder()}>
      <span class="head">{parts().head}</span><span class="tail">{parts().tail}</span>
    </span>
  );
}

/** A missing sample shows the size it last had, dimmed; one no check has found shows none. */
function Size(props: { s: SampleRow }) {
  return (
    <Show when={props.s.size_bytes != null}>
      <Show when={props.s.is_present} fallback={
        <span class="faint" title="Its size when a check last found it">{fmtBytes(props.s.size_bytes!)}</span>}>
        {fmtBytes(props.s.size_bytes!)}
      </Show>
    </Show>
  );
}

function Row(props: { s: SampleRow }) {
  return (
    <tr data-id={props.s.id} classList={{ sel: sui.selected === props.s.id }}
      onClick={() => select(props.s.id)}
      onContextMenu={(e) => {
        e.preventDefault();
        select(props.s.id);
        const win = (e.currentTarget as HTMLElement).closest(".win")!.getBoundingClientRect();
        setShell({ popover: null, menu: { id: props.s.id, x: e.clientX - win.left, y: e.clientY - win.top } });
      }}>
      <td><span class="n">{props.s.name}</span></td>
      <td>
        <span class="pstate" classList={{ "is-installed": props.s.is_present, "is-absent": !props.s.is_present }}>
          <PresentDot present={props.s.is_present} />{presenceLabel(props.s.is_present)}
        </span>
      </td>
      <td><Folder path={props.s.path} /></td>
      <td class="dim">{formatOf(props.s.path, formats()).name}</td>
      <td class="num"><Size s={props.s} /></td>
      <td class="num">{props.s.project_count || ""}</td>
    </tr>
  );
}

export function SampleTable() {
  return (
    <table class="grid fixed samples">
      <Head />
      <tbody><For each={pageRows()}>{(s) => <Row s={s} />}</For></tbody>
    </table>
  );
}
